- name: Install dnf-plugins-core
  dnf:
    name: dnf-plugins-core
    state: installed

# TODO introduce dnf module
- name: Set up the stable repository
  command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

- name: Install the latest version of Docker Engine - Community and containerd
  command: dnf -y install docker-ce docker-ce-cli containerd.io

- name: Cgroups Exception For Fedora 31, you’ll have to enable the backwards compatibility for Cgroups.
  command: grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"
  tags: "{{tag_fedora31}}"

- name: Enable Docker at boot
  command: systemctl enable docker

- name: Start Docker
  command: systemctl start docker

- name: Install docker-compose
  dnf:
    name: docker-compose
    state: installed