- name: GoBetween - create /root/gobetween
  file:
    path: /root/gobetween
    state: directory
    mode: u=rwx,g=rwx,o=rx #775
    owner: "{{ user_root }}"
    group: "{{ user_root }}"

- name: GoBetween copy docker-compose.yml
  template:
    src: ./stuff/load-balancers/GoBetween/docker/docker-compose.yml
    dest: /root/gobetween/docker-compose.yml
    mode: u=rw,g=rw,o=r #664
    owner: "{{ user_root }}"
    group: "{{ user_root }}"

- name: GoBetween copy configuration file
  template:
    src: ./stuff/load-balancers/GoBetween/config/gobetween.toml
    dest: /root/gobetween/gobetween.toml
    mode: u=rw,g=rw,o=r #664
    owner: "{{ user_root }}"
    group: "{{ user_root }}"

- name: GoBetween - stop docker containers
  command: docker-compose down
  ignore_errors: yes

- name: GoBetween - start docker containers
  command: docker-compose up -d -f /root/gobetween/docker-compose.yml
  ignore_errors: yes