- name: Install Terraform repository
  command: sudo dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
  args:
    warn: false

- name: Install Terraform
  dnf:
    name: "terraform"
    state: installed
    validate_certs: yes
  become: true
  become_user: "{{ user_root }}"
  ignore_errors: yes
