- name: VPN WireGuard - stop service
  command: wg-quick down wg0
  ignore_errors: true

- name: VPN WireGuard - sleep 3
  pause:
    seconds: 3

- name: VPN WireGuard - copy server configuration
  copy:
    src: ./stuff/services/vpn-wireguard/server/wg0.conf
    dest: /etc/wireguard/wg0.conf
    mode: u=rw,g=r,o=r #644
    owner: "{{ user_root }}"
    group: "{{ user_root }}"
  delegate_to: VM-1

- name: VPN WireGuard - copy client configuration
  copy:
    src: ./stuff/services/vpn-wireguard/client/wg0.conf
    dest: /etc/wireguard/wg0.conf
    mode: u=rw,g=r,o=r #644
    owner: "{{ user_root }}"
    group: "{{ user_root }}"
  delegate_to: VM-0



- name: VPN WireGuard - start service
  command: wg-quick up wg0

- name: VPN WireGuard - sleep 3
  pause:
    seconds: 3


#- name: VPN WireGuard - display config
#  command: wg show

#- name: VPN WireGuard - link wg0 with ip
#  shell: ip link add dev wg0 type wireguard
#  ignore_errors: true

#- name: VPN WireGuard - add private key to WireGuard interface
#  shell: wg set wg0 private-key ./keyPrivate listen-port 51820