version: '3.6'
services:
  nxlog:
    image: nxlog/nxlog-ce:2.10.2150
    container_name: nxlog
    ports:
      - "12201:12201"
    volumes:
      - ./nxlog/config/nxlog.conf:/etc/nxlog.conf
      - ./nxlog/files/input:/var/log
      - ./nxlog/files/output:/lib
    restart: on-failure