- name: Oracle 11XE - Copy RPM
  copy:
    src: "{{ oracle_11xe_rpm_location }}/{{ oracle_11xe_rpm_name }}"
    dest: "/root/oracle-xe-11.2.0-1.0.x86_64.rpm"
    mode: u=rx,g=rx,o=rx #775
    owner: root
    group: root

- name: Oracle 11XE - Install
  command: rpm -i oracle-xe-11.2.0-1.0.x86_64.rpm