- name: Oracle 11XE - SWAP file and it's permission
  file:
    path: /swapfile
    state: touch
    mode: 0600
    owner: "{{ user_root }}"
    group: "{{ user_root }}"

- name: Oracle 11XE - SWAP mount location
  command: dd if=/dev/zero of=/swapfile bs=2048k count=1536

- name: Oracle 11XE - SWAP create
  command: mkswap /swapfile

- name: Oracle 11XE - SWAP on
  command: swapon /swapfile

- name: Oracle 11XE - SWAP verify show
  command: swapon --show
  register: swaponresponse

- debug: msg="{{ swaponresponse.stdout_lines }}"

- name: Oracle 11XE - SWAP free
  command: free -h
  register: freeresponse

- debug: msg={{ freeresponse.stdout_lines }}