version: '3.6'
services:
  # http://<HOST>:9000/
  # The default login is guest guest
  rabbit-mq:
    container_name: rabbit-mq
    image: rabbitmq:3-management
    ports:
      - "9000:15672" # web UI port
      - "9200:5672" # TCP port
    user: root
