#- include_vars: definitions.yml

- name: Create group {{ user_group }}
  group:
    name: "{{user_group}}"
    state: present

- name: Create users
  user:
    name: "{{item.username}}"
    password: "{{item.password | password_hash('sha512') }}"
    create_home: yes
    update_password: always
    group: "{{user_group}}"
    shell: "{{item.shell}}"
    home: /home/{{item.username}}
  loop:
    - username: user1
      password: user1
      shell: /bin/bash
    - username: user2
      password: user2
      shell: /bin/bash