version: '3.6'
services:
  rabbit-mq:
    container_name: rabbit-mq
    image: rabbitmq:3-management
    ports:
      - "9000:15672"
      - "9001:5672"
    user: root
# http://localhost:9000/
# The default login is guest guest
#=======================================
