version: '3.6'

services:
  #http://localhost:8080
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
      
  #http://localhost:8081
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081"
      - "443:443"
    user: root
    volumes:
     - ./nexus:/nexus-data