version: '3.6'
services:

  #loclahost:5601 -> Kibana UI
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
    restart: on-failure
    depends_on:
      - elasticsearch

  graylog:
    image: graylog/graylog:3.0
    container_name: graylog
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    #links:
    #  - mongodb:mongo
    #  - elasticsearch
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - "9000:9000"
      # Syslog TCP
      - "1514:1514"
      # Syslog UDP
      #- 1514:1514/udp
      # GELF TCP
      #- 12201:12201
      # GELF UDP
      #- 12201:12201/udp

  nxlog:
    image: nxlog/nxlog-ce
    container_name: nxlog
    ports:
      - "12202:12202"
    volumes:
      - ./nxlog/nxlog.conf:/etc/nxlog.conf
    restart: on-failure

  #loclahost:9200 -> health check against ElasticSearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    restart: on-failure

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./mongodb:/data/db
    ports:
      - "27017:27017"