version: '3.6'
services:

  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.3
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300

