- name: Install yum-utils
  dnf:
    name: yum-utils
    state: installed

# TODO - warning is being displayed
- name: Set up the stable repository
  command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

- name: Install the latest version of Docker Engine - Community and containerd
  dnf:
    name: containerd.io
    state: installed

- name: Install Docker CE
  dnf:
    name: docker-ce
    state: installed

- name: Install Docker CE CLI
  dnf:
    name: docker-ce-cli
    state: installed

- name: Create cgroup directory for docker
  file:
    path: /sys/fs/cgroup/systemd
    state: directory
    mode: u=rwx,g=rwx,o=rwx #777
    owner: "{{user_root}}"
    group: "{{user_root}}"

#TODO try to use Ansible Mount
- name: Cgroup mounting
  command: mount -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd
  ignore_errors: yes

- name: Enable Docker at boot
  command: systemctl enable docker

- name: Reload Docker daemon
  command: systemctl daemon-reload

- name: Start Docker daemon
  command: systemctl start docker.service

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: "{{ docker_compose_path }}"
    mode: 0755

- name: Apply executable permissions to docker-compose binary
  file:
    path: "{{ docker_compose_path }}"
    mode:  u=rwx,g=rwx,o=rwx