- name: Docker post install - chkconfig for docker - may be required especially on RedHat/Centos
  command: chkconfig docker on
  ignore_errors: yes

- name: Docker post install - create docker group - may be required especially on RedHat/Centos
  command: groupadd docker
  ignore_errors: yes

- name: Docker post install - add yourself to docker group
  command: usermod -aG docker $USER
  ignore_errors: yes

- name: Docker post install - Docker cgroups
  command: grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"
  ignore_errors: yes