- name: Random logger - Create  directory
  file:
    path: /root/random-logger
    state: directory
    mode: '0755'

- name: Random logger - Copy docker-compose
  template:
    src: ./stuff/services/random-logger/docker-compose.yml
    dest: /root/rabbit-mq/docker-compose.yml
    mode: u=rw,g=rw,o=r #664
    owner: "{{ user_root }}"
    group: "{{ user_root }}"

- name: Random logger  - Enable and restart services
  community.general.docker_compose:
    project_src: /root/random-logger
    build: no
    restarted: yes
    state: present