- name: Oracle 11XE - Create  directory
  file:
    path: /root/oracle-11xe
    state: directory
    mode: '0755'

- name: Oracle 11XE - Copy docker-compose.yml
  template:
    src: ./stuff/databases/oracle/11xe/docker/docker-compose.yml
    dest: /root/oracle-11xe/docker-compose.yml
    mode: u=rw,g=rw,o=r #664
    owner: "{{ user_root }}"
    group: "{{ user_root }}"

- name: Oracle 11XE - Enable and restart services
  community.general.docker_compose:
    project_src: /root/oracle-11xe
    build: no
    restarted: yes
    state: present