version: '3.6'

services:
  oracle-db-12c-se:
    image: quay.io/maksymbilenko/oracle-12c
    ports:
      - "8080:8080"
      - "1521:1521"
    environment:
      - processes=200
      - DATABASES=sample
    volumes:
      - ./oracle:/u01/app/oracle
      - ./oracle-sql:/docker-entrypoint-initdb.d