version: '3.7'

services:
  openldap:
    image: bitnami/openldap:2
    ports:
      - "1389:1389"
      - "1636:1636"
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminPswd
      - LDAP_USERS=user01 #,user02
      - LDAP_PASSWORDS=uPsw1 #,uPsw2
      # - LDAP_PORT_NUMBER: The port OpenLDAP is listening for requests. Default: 1389 (non privileged port)
      # - LDAP_ROOT: LDAP database root node of the LDAP tree. Default: dc=example,dc=org
      # - LDAP_USER_DC: DC for the users' organizational unit. Default: users
      # - LDAP_GROUP: Group used to group created users. Default: readers
    volumes:
      - ./data:/bitnami/openldap
    restart: always