version: '3.6'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080"
    volumes:
      - ./jenskins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    deploy:
      mode: replicated
      replicas: 1
   
#http://SERVER_DOMAIN:8081

  artifactory:
    container_name: artifactory
    image: docker.bintray.io/jfrog/artifactory-pro:latest
    ports:
      - "8082:8081"
    volumes:
      - ./artifactory:/var/opt/jfrog/artifactory
    user: root  
    deploy:
      mode: replicated
      replicas: 0
    depends_on:
      - jenkins
      
#http://SERVER_DOMAIN:8082/artifactory
