version: '3.6'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080"
    volumes:
      - ./jenskins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
   
#http://localhost:8081

  artifactory:
    container_name: artifactory
    image: docker.bintray.io/jfrog/artifactory-pro:latest
    ports:
      - "8082:8081"
    volumes:
      - ./artifactory:/var/opt/jfrog/artifactory
    user: root  
    depends_on:
      - jenkins
      
#http://localhost:8082/artifactory


  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8083:8081"
    user: root  
    volumes:
      - ./nexus:/nexus-data
    depends_on:
     - jenkins
     - artifactory
# http://localhost:8083      
