- name: Install dnf-plugins-core
  dnf:
    name: dnf-plugins-core
    state: installed

- name: Install yum-utils
  dnf:
    name: yum-utils
    state: installed

# TODO introduce dnf module
- name: Set up the stable repository
  command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

# TODO introduce dnf module
- name: Install the latest version of Docker Engine - Community and containerd
  command: dnf -y install containerd.io

- name: Install Docker CE
  dnf:
    name: docker-ce
    state: installed

- name: Install Docker CE CLI
  dnf:
    name: docker-ce-cli
    state: installed

- name: Enable Docker at boot
  command: systemctl enable docker

- name: Chconfig for Docker
  command: chkconfig docker on

- name: Reload Docker daemon
  command: systemctl daemon-reload

- name: Start Docker daemon
  command: systemctl start docker.service

#------------------------------------------------------------------------------------------------
- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: "{{ docker_compose_path }}"
    mode: 0755

- name: Apply executable permissions to docker-compose binary
  file:
    path: "{{ docker_compose_path }}"
    mode:  u=rwx,g=rwx,o=rwx