- name: Create  directory for Rabbit-MQ
  file:
    path: /root/rabbot-mq
    state: directory
    mode: '0755'

- name: Copy docker-compose for Rabbit-MQ
  copy:
    src: ./stuff/rabbit-mq/docker-compose.yml
    dest: /root/docker-compose.yml
    mode: u=rw,g=rw,o=r #664
    owner: "{{ user_root }}"
    group: "{{ user_root }}"