- name: Rabbit-MQ - copy docker-compose
  template:
    src: ./stuff/rabbit-mq/docker-compose.yml
    dest: "{{ installation_directory }}/docker-compose.yml"
    mode: u=rw,g=rw,o=r #664
    owner: "{{ user_root }}"
    group: "{{ user_root }}"

- name: Rabbit-MQ - stop docker containers
  command: docker-compose down
  ignore_errors: yes

- name: Rabbit-MQ - start docker containers
  command: docker-compose up -d
  ignore_errors: yes