version: '3.6'

#http://localhost:8081
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
      
  #http://localhost:8083
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8083:8081"
      - "443:443"
    user: root
    volumes:
     - ./nexus:/nexus-data

  #http://localhost:8082/ui
  #requires license and $$$ - cannot afford for this now
  # admin/password
  #artifactory:
  #  container_name: artifactory
  #  image: docker.bintray.io/jfrog/artifactory-pro:latest
  #  ports:
  #    - "8082:8082"
  #    - "8081:8081"
  #    - "8046:8046"
  #    - "8070:8070"
  #  volumes:
  #    - ./artifactory:/var/opt/jfrog/artifactory
  #  user: root