- name: SDKMAN - Install zip
  dnf:
    name: zip
    state: latest

- name: SDKMAN - Install unzip
  dnf:
    name: unzip
    state: latest

- name: SDKMAN - Download SDKMAN script
  get_url:
    url: https://get.sdkman.io
    dest: /sdkman-script.sh
    mode: 0777

- name: SDKMAN - Install sdkman
  command: /sdkman-script.sh