- name: Linux - Install Signal
  command: snap install signal-desktop
  become: true
  become_user: "{{ user_root }}"
  ignore_errors: yes

- name: Linux - Refresh Signal
  command: snap refresh signal-desktop
  become: true
  become_user: "{{ user_root }}"
  ignore_errors: yes