- name: Linux snapd - installation
  dnf:
    name: snapd
    state: installed
  become: true
  become_user: "{{ user_root }}"
  ignore_errors: yes

- name: Linux snapd - linking
  command: ln -s /var/lib/snapd/snap /snap
  become: true
  become_user: "{{ user_root }}"
  ignore_errors: yes

- name: Linux snapd - Copy config file
  template:
    src: ./stuff/localhost/linux/snapd
    dest: /etc/sysconfig/snapd
    mode: u=rwx,g=rwx,o=rwx #777
    owner: "{{ user_root }}"
    group: "{{ user_root }}"