- name: Form a cluster - peer nodes.
  command: "gluster peer probe {{ peernode }}"
  loop: "{{ ansible_play_hosts | flatten(levels=1) }}"
  loop_control:
    loop_var: peernode
    pause: 2
  register: glusterpeerprobe
  become: true
  run_once: true
  any_errors_fatal: true
  changed_when: "'peer probe: success.' in glusterpeerprobe.stdout_lines"

- name: Create gluster volume
  file:
    path: /{{ gluster_volume_name }}
    state: directory
    mode: u=rwx,g=rwx,o=rwx #777
    owner: "{{ user_root }}"
    group: "{{ user_root }}"

- name: Mount gluster volume
  gluster.gluster.gluster_volume:
    state: present
    name: "{{ gluster_volume_name }}"
    bricks: /{{ gluster_volume_name }}
    rebalance: yes
    cluster: "{{ hostvars | join(',') }}"
    force: true # has to be forced when you mount at root partition brick
  run_once: true

- name: Start gluster volume
  gluster.gluster.gluster_volume:
    state: started
    name: "{{ gluster_volume_name }}"