- name: VPN WireGuard - install service
  dnf:
    name: wireguard-tools
    state: installed
  tags: "{{ tag_wireguard_install }}"

- name: VPN WireGuard - generate key pair for Server
  shell: wg genkey | tee keyPrivateServer | wg pubkey > keyPublicServer
  delegate_to: VM-1
  tags: "{{ tag_wireguard_keys }}"
- name: VPN WireGuard - generate key pair for Client
  shell: wg genkey | tee keyPrivateClient | wg pubkey > keyPublicClient
  delegate_to: VM-0
  tags: "{{ tag_wireguard_keys }}"