- hosts: "{{ target_server_group }}"
  remote_user: "{{ user_root }}"
  gather_facts: True
  vars_files:
    - variables-common.yml
    - variables-installation.yml
  tasks:
    - import_tasks: ./tasks/linux/dnf.yml
      tags: "{{ tag_dnf }}"
    - import_tasks: ./tasks/linux/sdkman.yml
      tags: "{{ tag_sdkman }}"
    - import_tasks: ./tasks/linux/users/users.yml
      tags: "{{ tag_users}}"
    - import_tasks: ./tasks/linux/hosts.yml
      tags: "{{ tag_routing }}"
    - import_tasks: ./tasks/docker/docker.yml
      tags: "{{ tag_docker }}"
    - import_tasks: ./tasks/extensions/extensions.yml
      tags: "{{ tag_extensions }}"