# this locally generates keys/ they are saved in ./stuff/services/vpn-wireguard/keys
- name: VPN WireGuard - generate key pair for Server
  shell: wg genkey | tee keyPrivateServer | wg pubkey > keyPublicServer
  delegate_to: VM-1

- name: VPN WireGuard - generate key pair for Client
  shell: wg genkey | tee keyPrivateClient | wg pubkey > keyPublicClient
  delegate_to: VM-0

- name: VPN WireGuard - copy sysctl.conf with IP V4 setup
  copy:
    src: ./stuff/services/vpn-wireguard/sysctl.conf
    dest: /etc/sysctl.conf
    mode: u=rw,g=r,o=r #644
    owner: "{{ user_root }}"
    group: "{{ user_root }}"

- name: VPN Wireguard - reload sysctl
  command: sysctl -p

- name: VPN WireGuard - dependency iptables
  dnf:
    name: iptables
    state: installed

- name: VPN WireGuard - install service
  dnf:
    name: wireguard-tools
    state: installed

- name: VPN WireGuard - copy server configuration
  copy:
    src: ./stuff/services/vpn-wireguard/server/wg0.conf
    dest: /etc/wireguard/wg0.conf
    mode: u=rw,g=r,o=r #644
    owner: "{{ user_root }}"
    group: "{{ user_root }}"
  delegate_to: VM-1

- name: VPN WireGuard - copy client configuration
  copy:
    src: ./stuff/services/vpn-wireguard/client/wg0.conf
    dest: /etc/wireguard/wg0.conf
    mode: u=rw,g=r,o=r #644
    owner: "{{ user_root }}"
    group: "{{ user_root }}"
  delegate_to: VM-0

#- name: VPN WireGuard - stop service
#  command: wg-quick down wg0
#  ignore_errors: true

#- name: VPN WireGuard - start service
#  command: wg-quick up wg0

#- name: VPN WireGuard - display config
#  command: wg show

#- name: VPN WireGuard - link wg0 with ip
#  shell: ip link add dev wg0 type wireguard
#  ignore_errors: true

#- name: VPN WireGuard - add private key to WireGuard interface
#  shell: wg set wg0 private-key ./keyPrivate listen-port 51820