- name: VPN WireGuard - dependency iptables
  dnf:
    name: iptables
    state: installed

- name: VPN WireGuard - install
  dnf:
    name: wireguard-tools
    state: installed

- name: VPN WireGuard - generate key pair
  shell: wg genkey | tee keyPrivate | wg pubkey > keyPublic

- name: VPN WireGuard - link wg0 with ip
  shell: ip link add dev wg0 type wireguard
  ignore_errors: true

- name: VPN WireGuard - add private key to WireGuard interface
  shell: wg set wg0 private-key ./keyPrivate listen-port 51820