- import_tasks: ./common/wireguard-common.yml
- import_tasks: ./manual/wireguard-manual.yml
  tags: "{{ tag_wireguard_install_manual }}"
#- import_tasks: ./automated/wireguard-automated.yml
#  tags: "{{ tag_wireguard_install_automation }}"